import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCKS = (
    ROOT / "requirements-bootstrap.lock",
    ROOT / "requirements.lock",
    ROOT / "requirements-dev.lock",
)


def test_python_locks_are_complete_and_hashed():
    requirement = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*(?:==| @ )")
    for path in LOCKS:
        contents = path.read_text(encoding="utf-8")
        assert "autogenerated by pip-compile with Python 3.14" in contents
        assert "CUSTOM_COMPILE_COMMAND" not in contents
        entries = [line for line in contents.splitlines() if requirement.match(line)]
        assert entries
        assert all("==" in line or "#sha256=" in line for line in entries)
        assert contents.count("--hash=sha256:") >= len(entries)


def test_production_and_development_locks_have_deliberate_scope():
    production = (ROOT / "requirements.lock").read_text(encoding="utf-8")
    development = (ROOT / "requirements-dev.lock").read_text(encoding="utf-8")
    bootstrap = (ROOT / "requirements-bootstrap.lock").read_text(encoding="utf-8")
    assert "fastpasskey @ https://github.com/Malaber/python-libs/releases/" in production
    assert "bandit==" not in production
    assert "pytest==" not in production
    assert "bandit==1.9.4" in development
    assert "pip-audit==2.10.1" in development
    assert "pip-tools==7.6.0" in development
    assert "invoke==3.0.3" in bootstrap


def test_dependency_audit_preserves_hashes_and_scans_direct_artifact_code():
    tasks = (ROOT / "tasks.py").read_text(encoding="utf-8")
    assert "--disable-pip --require-hashes --strict" in tasks
    assert '_installed_package_path("fastpasskey")' in tasks
